default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: lucas
  password: lucas

development:
  <<: *default
  database: invoice_generator_development

test:
  <<: *default
  database: invoice_generator_test

production:
  <<: *default
  database: invoice_generator_production
  username: invoice_generator
  password: <%= ENV['INVOICE_GENERATOR_DATABASE_PASSWORD'] %>
